WITH CTE AS (
select

TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) as DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) as HOUR_STARTED_AT,

CASE 
when  DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
then 'WEEKEND'
else 'BUSINESSDAY'
END as DAY_TYPE,

CASE
when MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2)
then 'WINTER'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (5,3,4)
then 'SPRING'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8)
then 'SUMMER'
ELSE 'AUTUM'
END as STATION_OF_YEAR

from  
{{ source('demo', 'bike') }}
)

select * from CTE